export const MIN_AIRPORT_PICKUP_PASSENGERS = 1;
export const MAX_AIRPORT_PICKUP_PASSENGERS = 8;

export const AIRPORT_PICKUP_PASSENGER_OPTIONS = Array.from(
  { length: MAX_AIRPORT_PICKUP_PASSENGERS - MIN_AIRPORT_PICKUP_PASSENGERS + 1 },
  (_, index) => MIN_AIRPORT_PICKUP_PASSENGERS + index,
);
